.TH "inc/EGL/buffer.h" 3 "Easy OpenGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/EGL/buffer.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <cstdint>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBegl::Buffer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBegl\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBegl::BufferType\fP { \fBegl::Array\fP, \fBegl::AtomicCounter\fP, \fBegl::CopyRead\fP, \fBegl::CopyWrite\fP, \fBegl::DispatchIndirect\fP, \fBegl::DrawIndirect\fP, \fBegl::ElementArray\fP, \fBegl::PixelPack\fP, \fBegl::PixelUnpack\fP, \fBegl::Query\fP, \fBegl::ShaderStorage\fP, \fBegl::Texture\fP, \fBegl::TransformFeedback\fP, \fBegl::Uniform\fP }"
.br
.RI "Enum to indicate the type of \fBBuffer\fP\&. "
.ti -1c
.RI "enum class \fBegl::BufferUsage\fP { \fBegl::StreamDraw\fP, \fBegl::StreamRead\fP, \fBegl::StreamCopy\fP, \fBegl::StaticDraw\fP, \fBegl::StaticRead\fP, \fBegl::StaticCopy\fP, \fBegl::DynamicDraw\fP, \fBegl::DynamicRead\fP, \fBegl::DynamicCopy\fP }"
.br
.RI "Enum to indicate \fBBuffer\fP Usage\&. "
.ti -1c
.RI "enum class \fBegl::MapUsage\fP : uint32_t { \fBegl::None\fP = 0, \fBegl::Read\fP = 1 << 0, \fBegl::Write\fP = 1 << 1, \fBegl::Persistent\fP = 1 << 2, \fBegl::Coherent\fP = 1 << 3, \fBegl::InvalidRange\fP = 1 << 4, \fBegl::InvalidateBuffer\fP = 1 << 5, \fBegl::FlushExplicit\fP = 1 << 6, \fBegl::Unsynchronized\fP = 1 << 7 }"
.br
.RI "Enum flags to indicate \fBBuffer\fP map usage\&. "
.ti -1c
.RI "enum class \fBegl::BufferFlag\fP : uint32_t { \fBegl::None\fP = 0, \fBegl::DynamicStorage\fP = 1 << 0, \fBegl::MapRead\fP = 1 << 1, \fBegl::MapWrite\fP = 1 << 2, \fBegl::MapPersistent\fP = 1 << 3, \fBegl::MapCoherent\fP = 1 << 4, \fBegl::ClientStorage\fP = 1 << 5 }"
.br
.RI "Enum falgs for explicit \fBBuffer\fP usage in setStorage\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMapUsage\fP \fBegl::operator|\fP (\fBMapUsage\fP a, \fBMapUsage\fP b)"
.br
.ti -1c
.RI "\fBMapUsage\fP \fBegl::operator&\fP (\fBMapUsage\fP a, \fBMapUsage\fP b)"
.br
.ti -1c
.RI "\fBMapUsage\fP & \fBegl::operator|=\fP (\fBMapUsage\fP &a, \fBMapUsage\fP b)"
.br
.ti -1c
.RI "\fBBufferFlag\fP \fBegl::operator|\fP (\fBBufferFlag\fP a, \fBBufferFlag\fP b)"
.br
.ti -1c
.RI "\fBBufferFlag\fP \fBegl::operator&\fP (\fBBufferFlag\fP a, \fBBufferFlag\fP b)"
.br
.ti -1c
.RI "\fBBufferFlag\fP & \fBegl::operator|=\fP (\fBBufferFlag\fP &a, \fBBufferFlag\fP b)"
.br
.ti -1c
.RI "unsigned int \fBegl::toGLenum\fP (\fBBufferType\fP type)"
.br
.ti -1c
.RI "unsigned int \fBegl::toGLenum\fP (\fBBufferUsage\fP usage)"
.br
.ti -1c
.RI "unsigned int \fBegl::toGLenum\fP (\fBMapUsage\fP usage)"
.br
.ti -1c
.RI "unsigned int \fBegl::toGLenum\fP (\fBBufferFlag\fP flag)"
.br
.ti -1c
.RI "bool \fBegl::validateMapUsage\fP (\fBMapUsage\fP usage, std::string &error)"
.br
.ti -1c
.RI "bool \fBegl::validateBufferFlag\fP (\fBBufferFlag\fP flag, std::string &error)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy OpenGL from the source code\&.
