.TH "egl::_uniformData" 3 "Easy OpenGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
egl::_uniformData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <program\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlocation\fP"
.br
.ti -1c
.RI "unsigned int \fBglType\fP"
.br
.ti -1c
.RI "int \fBarraySize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int egl::_uniformData::arraySize"

.SS "unsigned int egl::_uniformData::glType"

.SS "int egl::_uniformData::location"


.SH "Author"
.PP 
Generated automatically by Doxygen for Easy OpenGL from the source code\&.
