.TH "egl::Program::UniformProxyConst" 3 "Easy OpenGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
egl::Program::UniformProxyConst
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <program\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniformProxyConst\fP (const \fBProgram\fP &parent, int location)"
.br
.ti -1c
.RI "\fBUniformProxyConst\fP (UniformProxyConst &&other)=delete"
.br
.ti -1c
.RI "\fBUniformProxyConst\fP (const UniformProxyConst &other)=delete"
.br
.ti -1c
.RI "\fBoperator float\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::vec2\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::vec3\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::vec4\fP () const"
.br
.ti -1c
.RI "\fBoperator int\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::ivec2\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::ivec3\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::ivec4\fP () const"
.br
.ti -1c
.RI "\fBoperator unsigned int\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::uvec2\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::uvec3\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::uvec4\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat2\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat3\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat4\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat2x3\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat3x2\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat2x4\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat4x2\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat3x4\fP () const"
.br
.ti -1c
.RI "\fBoperator glm::mat4x3\fP () const"
.br
.ti -1c
.RI "\fBUniformProxyConst\fP & \fBoperator=\fP (const \fBUniformProxyConst\fP &other)=delete"
.br
.ti -1c
.RI "\fBUniformProxyConst\fP & \fBoperator=\fP (\fBUniformProxyConst\fP &&other)=delete"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "egl::Program::UniformProxyConst::UniformProxyConst (const \fBProgram\fP & parent, int location)\fR [inline]\fP"

.SS "egl::Program::UniformProxyConst::UniformProxyConst (UniformProxyConst && other)\fR [delete]\fP"

.SS "egl::Program::UniformProxyConst::UniformProxyConst (const UniformProxyConst & other)\fR [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "egl::Program::UniformProxyConst::operator float () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::ivec2 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::ivec3 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::ivec4 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat2 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat2x3 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat2x4 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat3 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat3x2 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat3x4 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat4 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat4x2 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::mat4x3 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::uvec2 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::uvec3 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::uvec4 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::vec2 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::vec3 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator glm::vec4 () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator int () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "egl::Program::UniformProxyConst::operator unsigned int () const\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBUniformProxyConst\fP & egl::Program::UniformProxyConst::operator= (const \fBUniformProxyConst\fP & other)\fR [delete]\fP"

.SS "\fBUniformProxyConst\fP & egl::Program::UniformProxyConst::operator= (\fBUniformProxyConst\fP && other)\fR [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Easy OpenGL from the source code\&.
