.TH "md_inc_2_e_g_l_2mainpage" 3 "Easy OpenGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_inc_2_e_g_l_2mainpage \- Introduction 
.PP


.PP
This project provides a low-level OpenGL abstraction implemented in modern C++, using try-catch based error handling and classes representing various OpenGL objects\&.
.SH "Recommended Setup"
.PP
The recommended setup is to have your main code class inherit from \fR\fBegl::WindowContext\fP\fP and implement your logic in the provided virtual run function\&.

.PP
Calling \fR\fBegl::WindowContext::useContext\fP\fP is recommended to avoid potential errors\&.

.PP
Inside of \fR\fBegl::WindowContext::run\fP\fP any Easy OpenGL functionality can be used safely\&. 
