.TH "inc/GLA/program.h" 3 "OpenGL Abstraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/GLA/program.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <glm/vec2\&.hpp>\fP
.br
\fR#include <glm/vec3\&.hpp>\fP
.br
\fR#include <glm/vec4\&.hpp>\fP
.br
\fR#include <glm/matrix\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgla::ProgramLinkError\fP"
.br
.RI "Exception thrown when \fBProgram\fP linking fails\&. "
.ti -1c
.RI "class \fBgla::ProgramValidateError\fP"
.br
.RI "Exception thrown when \fBProgram\fP validation fails, mainly used in debug builds\&. "
.ti -1c
.RI "struct \fBgla::_uniformData\fP"
.br
.ti -1c
.RI "class \fBgla::Program\fP"
.br
.RI "\fBProgram\fP class to abstract OpenGL \fBShader\fP Programs\&. "
.ti -1c
.RI "class \fBgla::Program::UniformProxy\fP"
.br
.ti -1c
.RI "class \fBgla::Program::UniformProxyConst\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgla\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBgla::_uniformData\fP \fBgla::UniformData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Abstraction from the source code\&.
