.TH "inc/EGL/shader.h" 3 "Easy OpenGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/EGL/shader.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <iosfwd>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBegl::ShaderCompileError\fP"
.br
.RI "Exception thrown when \fBShader\fP compilation fails\&. "
.ti -1c
.RI "class \fBegl::Shader\fP"
.br
.RI "\fBShader\fP class to abstract OpenGL Shaders\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBegl\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBegl::ShaderType\fP { \fBegl::Fragment\fP, \fBegl::Vertex\fP, \fBegl::Geometry\fP, \fBegl::TessEvaluation\fP, \fBegl::TessControl\fP, \fBegl::Compute\fP }"
.br
.RI "\fBShaderType\fP enum to indicate usage\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr std::string \fBegl::shaderTypeToString\fP (\fBShaderType\fP type)"
.br
.RI "Converts the \fBShaderType\fP enum into a std::string\&. "
.ti -1c
.RI "unsigned int \fBegl::toGLenum\fP (\fBShaderType\fP type)"
.br
.RI "Converts the \fBShaderType\fP enum into an OpenGL enum\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy OpenGL from the source code\&.
