.TH "inc/GLA/shader.h" 3 "OpenGL Abstraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/GLA/shader.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <iosfwd>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgla::ShaderCompileError\fP"
.br
.RI "Exception thrown when \fBShader\fP compilation fails\&. "
.ti -1c
.RI "class \fBgla::Shader\fP"
.br
.RI "\fBShader\fP class to abstract OpenGL Shaders\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgla\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBgla::ShaderType\fP { \fBgla::Fragment\fP, \fBgla::Vertex\fP, \fBgla::Geometry\fP, \fBgla::TessEvaluation\fP, \fBgla::TessControl\fP, \fBgla::Compute\fP }"
.br
.RI "\fBShaderType\fP enum to indicate usage\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "constexpr std::string \fBgla::shaderTypeToString\fP (\fBShaderType\fP type)"
.br
.RI "Converts the \fBShaderType\fP enum into a std::string\&. "
.ti -1c
.RI "unsigned int \fBgla::toGLenum\fP (\fBShaderType\fP type)"
.br
.RI "Converts the \fBShaderType\fP enum into an OpenGL enum\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Abstraction from the source code\&.
