.TH "inc/GLA/windowContext.h" 3 "OpenGL Abstraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/GLA/windowContext.h
.SH SYNOPSIS
.br
.PP
\fR#include <GLFW/glfw3\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgla::WindowContext\fP"
.br
.RI "An abstract class to contain an window based application\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgla\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBgla::initGLFW\fP ()"
.br
.RI "Initialize GLFW\&. "
.ti -1c
.RI "void \fBgla::terminateGLFW\fP ()"
.br
.RI "Terminates GLFW\&. "
.ti -1c
.RI "void \fBgla::pollEvents\fP ()"
.br
.RI "Polls GLFW events\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Abstraction from the source code\&.
