.TH "inc/EGL/windowContext.h" 3 "Easy OpenGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/EGL/windowContext.h
.SH SYNOPSIS
.br
.PP
\fR#include <GLFW/glfw3\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBegl::WindowContext\fP"
.br
.RI "An abstract class to contain an window based application\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBegl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBegl::initGLFW\fP ()"
.br
.RI "Initialize GLFW\&. "
.ti -1c
.RI "void \fBegl::terminateGLFW\fP ()"
.br
.RI "Terminates GLFW\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Easy OpenGL from the source code\&.
